# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'retoucheImage.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1611, 826)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(115,115, 115);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(830, 150, 661, 491))
        self.widget_2.setStyleSheet("background-color: rgb(0,0,0)")
        self.widget_2.setObjectName("widget_2")
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 641, 471))
        self.label_4.setStyleSheet("background-color: rgb(255,255,255)")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 110, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1130, 100, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(40, 150, 661, 491))
        self.widget_3.setStyleSheet("background-color: rgb(0,0,0)")
        self.widget_3.setObjectName("widget_3")
        self.label_5 = QtWidgets.QLabel(self.widget_3)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 641, 471))
        self.label_5.setStyleSheet("background-color: rgb(255,255,255)")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(730, 350, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(1110, 670, 160, 18))
        self.horizontalSlider.setStyleSheet("selection-background-color: rgb(255, 0, 0);")
        self.horizontalSlider.setMaximum(255)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(1110, 700, 160, 18))
        self.horizontalSlider_2.setStyleSheet("selection-background-color: rgb(0, 255, 0);")
        self.horizontalSlider_2.setMaximum(255)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalSlider_3 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_3.setGeometry(QtCore.QRect(1110, 730, 160, 18))
        self.horizontalSlider_3.setStyleSheet("selection-background-color: rgb(0, 0, 255);")
        self.horizontalSlider_3.setMaximum(255)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(1290, 670, 64, 23))
        self.lcdNumber.setObjectName("lcdNumber")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_2.setGeometry(QtCore.QRect(1290, 700, 64, 23))
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_3.setGeometry(QtCore.QRect(1290, 730, 64, 23))
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(980, 650, 111, 111))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("220px-Colors-i54-ring.png"))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(70, 50, 63, 20))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(70, 90, 63, 20))
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(20, 10, 101, 91))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("retouche.png"))
        self.label_9.setObjectName("label_9")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1611, 25))
        self.menubar.setTabletTracking(False)
        self.menubar.setStyleSheet("background-color:rgb(255,255,255)")
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setStyleSheet("")
        self.menuFile.setObjectName("menuFile")
        self.menuTraitement = QtWidgets.QMenu(self.menubar)
        self.menuTraitement.setObjectName("menuTraitement")
        self.menuRetouche = QtWidgets.QMenu(self.menubar)
        self.menuRetouche.setObjectName("menuRetouche")
        self.menuEdition = QtWidgets.QMenu(self.menubar)
        self.menuEdition.setObjectName("menuEdition")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOuvrir = QtWidgets.QAction(MainWindow)
        self.actionOuvrir.setObjectName("actionOuvrir")
        self.actionEnregistrer_image = QtWidgets.QAction(MainWindow)
        self.actionEnregistrer_image.setObjectName("actionEnregistrer_image")
        self.actionQuitter = QtWidgets.QAction(MainWindow)
        self.actionQuitter.setObjectName("actionQuitter")
        self.actionRotation_180 = QtWidgets.QAction(MainWindow)
        self.actionRotation_180.setObjectName("actionRotation_180")
        self.actionRotation_90 = QtWidgets.QAction(MainWindow)
        self.actionRotation_90.setObjectName("actionRotation_90")
        self.actionRotation_91 = QtWidgets.QAction(MainWindow)
        self.actionRotation_91.setObjectName("actionRotation_91")
        self.actionNiveau_de_gris = QtWidgets.QAction(MainWindow)
        self.actionNiveau_de_gris.setObjectName("actionNiveau_de_gris")
        self.actionN_gatif = QtWidgets.QAction(MainWindow)
        self.actionN_gatif.setObjectName("actionN_gatif")
        self.actionPhotomaton = QtWidgets.QAction(MainWindow)
        self.actionPhotomaton.setObjectName("actionPhotomaton")
        self.actionPhotomaton_2 = QtWidgets.QAction(MainWindow)
        self.actionPhotomaton_2.setObjectName("actionPhotomaton_2")
        self.actionAnnuler = QtWidgets.QAction(MainWindow)
        self.actionAnnuler.setObjectName("actionAnnuler")
        self.actionMirroir = QtWidgets.QAction(MainWindow)
        self.actionMirroir.setObjectName("actionMirroir")
        self.menuFile.addAction(self.actionOuvrir)
        self.menuFile.addAction(self.actionEnregistrer_image)
        self.menuFile.addAction(self.actionQuitter)
        self.menuTraitement.addSeparator()
        self.menuTraitement.addAction(self.actionRotation_180)
        self.menuTraitement.addAction(self.actionMirroir)
        self.menuTraitement.addAction(self.actionRotation_90)
        self.menuTraitement.addAction(self.actionRotation_91)
        self.menuRetouche.addAction(self.actionNiveau_de_gris)
        self.menuRetouche.addAction(self.actionN_gatif)
        self.menuRetouche.addAction(self.actionPhotomaton)
        self.menuEdition.addAction(self.actionAnnuler)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdition.menuAction())
        self.menubar.addAction(self.menuTraitement.menuAction())
        self.menubar.addAction(self.menuRetouche.menuAction())

        self.retranslateUi(MainWindow)
        self.horizontalSlider.valueChanged['int'].connect(self.lcdNumber.display)
        self.horizontalSlider_2.valueChanged['int'].connect(self.lcdNumber_2.display)
        self.horizontalSlider_3.valueChanged['int'].connect(self.lcdNumber_3.display)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pix - Retouche d\'image"))
        self.label.setText(_translate("MainWindow", "Image normale"))
        self.label_2.setText(_translate("MainWindow", "Image retouchée"))
        self.label_3.setText(_translate("MainWindow", "→"))
        self.menuFile.setTitle(_translate("MainWindow", "Fichier"))
        self.menuTraitement.setTitle(_translate("MainWindow", "Traitement"))
        self.menuRetouche.setTitle(_translate("MainWindow", "Retouche"))
        self.menuEdition.setTitle(_translate("MainWindow", "Edition"))
        self.actionOuvrir.setText(_translate("MainWindow", "Ouvrir"))
        self.actionEnregistrer_image.setText(_translate("MainWindow", "Enregistrer image"))
        self.actionQuitter.setText(_translate("MainWindow", "Quitter"))
        self.actionRotation_180.setText(_translate("MainWindow", "Rotation 180°"))
        self.actionRotation_90.setText(_translate("MainWindow", "Rotation 90°"))
        self.actionRotation_91.setText(_translate("MainWindow", "Rotation -90°"))
        self.actionNiveau_de_gris.setText(_translate("MainWindow", "Niveau de gris"))
        self.actionN_gatif.setText(_translate("MainWindow", "Négatif"))
        self.actionPhotomaton.setText(_translate("MainWindow", "Photomaton"))
        self.actionPhotomaton_2.setText(_translate("MainWindow", "Photomaton +"))
        self.actionAnnuler.setText(_translate("MainWindow", "Annuler"))
        self.actionMirroir.setText(_translate("MainWindow", "Mirroir"))
