# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'listePossibilite.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_listePossibilite(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1170, 484)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 181, 91))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/reponses/airplane.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(210, 10, 181, 91))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("images/reponses/apple.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(400, 10, 181, 91))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("images/reponses/book.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(780, 10, 181, 91))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("images/reponses/car.jpg"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(590, 10, 181, 91))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("images/reponses/brain.jpg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(970, 10, 181, 91))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("images/reponses/chair.jpg"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(970, 110, 181, 91))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("images/reponses/The Eiffel Tower.jpg"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(210, 110, 181, 91))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("images/reponses/eye.jpg"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(590, 110, 181, 91))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("images/reponses/guitar.jpg"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(20, 110, 181, 91))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("images/reponses/dog.jpg"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(400, 110, 181, 91))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("images/reponses/face.jpg"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(780, 110, 181, 91))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("images/reponses/rabbit.jpg"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(590, 310, 181, 91))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("images/reponses/9.jpg"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(970, 210, 181, 91))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("images/reponses/5.jpg"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(210, 310, 181, 91))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("images/reponses/7.jpg"))
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(400, 310, 181, 91))
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("images/reponses/8.jpg"))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(210, 210, 181, 91))
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap("images/reponses/1.jpg"))
        self.label_19.setScaledContents(True)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(20, 310, 181, 91))
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap("images/reponses/6.jpg"))
        self.label_20.setScaledContents(True)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(590, 210, 181, 91))
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap("images/reponses/3.jpg"))
        self.label_21.setScaledContents(True)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(20, 210, 181, 91))
        self.label_22.setText("")
        self.label_22.setPixmap(QtGui.QPixmap("images/reponses/0.jpg"))
        self.label_22.setScaledContents(True)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(400, 210, 181, 91))
        self.label_23.setText("")
        self.label_23.setPixmap(QtGui.QPixmap("images/reponses/2.jpg"))
        self.label_23.setScaledContents(True)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(780, 210, 181, 91))
        self.label_24.setText("")
        self.label_24.setPixmap(QtGui.QPixmap("images/reponses/4.jpg"))
        self.label_24.setScaledContents(True)
        self.label_24.setObjectName("label_24")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1170, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Liste des possibiltiées"))